Having selected the group of  data about Seattle, we has information from Aipnb regarding this area. 
Below we will try diving into each dataset of this group to have a better understanding about the information that is included there. As a next step we will try investigate some interesting topics that can be answered by the data

1.We initialize all the necessary packages and uploadin the datasets

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 1000)


df_calendar = pd.read_csv('./calendar.csv')
df_listingsr = pd.read_csv('./listings.csv')
df_reviews = pd.read_csv('./reviews.csv')

2.We have a look of the top 3 rows of each DataFrame

In [2]:
df_calendar.head(3)

   listing_id        date available   price
0      241032  2016-01-04         t  $85.00
1      241032  2016-01-05         t  $85.00
2      241032  2016-01-06         f     NaN

In [3]:
df_listingsr.head(2)

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,241032,https://www.airbnb.com/rooms/241032,20160104002432,2016-01-04,Stylish Queen Anne Apartment,NaN,Make your self at home in this charming one-be...,Make your self at home in this charming one-be...,none,NaN,NaN,NaN,NaN,NaN,https://a1.muscache.com/ac/pictures/67560560/c...,NaN,956883,https://www.airbnb.com/users/show/956883,Maija,2011-08-11,"Seattle, Washington, United States","I am an artist, interior designer, and run a s...",within a few hours,96%,100%,f,https://a0.muscache.com/ac/users/956883/profil...,https://a0.muscache.com/ac/users/956883/profil...,Queen Anne,3.0,3.0,"['email', 'phone', 'reviews', 'kba']",t,t,"Gilman Dr W, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.636289,-122.371025,t,Apartment,Entire home/apt,4,1.0,1.0,1.0,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",NaN,$85.00,NaN,NaN,NaN,NaN,2,$5.00,1,365,4 weeks ago,t,14,41,71,346,2016-01-04,207,2011-11-01,2016-01-02,95.0,10.0,10.0,10.0,10.0,9.0,10.0,f,NaN,WASHINGTON,f,moderate,f,f,2,4.07
1,953595,https://www.airbnb.com/rooms/953595,20160104002432,2016-01-04,Bright & Airy Queen Anne Apartment,Chemically sensitive? We've removed the irrita...,"Beautiful, hypoallergenic apartment in an extr...",Chemically sensitive? We've removed the irrita...,none,"Queen Anne is a wonderful, truly functional vi...",What's up with the free pillows? Our home was...,"Convenient bus stops are just down the block, ...",https://a0.muscache.com/ac/pictures/14409893/f...,https://a0.muscache.com/im/pictures/14409893/f...,https://a0.muscache.com/ac/pictures/14409893/f...,https://a0.muscache.com/ac/pictures/14409893/f...,5177328,https://www.airbnb.com/users/show/5177328,Andrea,2013-02-21,"Seattle, Washington, United States",Living east coast/left coast/overseas. Time i...,within an hour,98%,100%,t,https://a0.muscache.com/ac/users/5177328/profi...,https://a0.muscache.com/ac/users/5177328/profi...,Queen Anne,6.0,6.0,"['email', 'phone', 'facebook', 'linkedin', 're...",t,t,"7th Avenue West, Seattle, WA 98119, United States",Queen Anne,West Queen Anne,Queen Anne,Seattle,WA,98119,Seattle,"Seattle, WA",US,United States,47.639123,-122.365666,t,Apartment,Entire home/apt,4,1.0,1.0,1.0,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",NaN,$150.00,"$1,000.00","$3,000.00",$100.00,$40.00,1,$0.00,2,90,today,t,13,13,16,291,2016-01-04,43,2013-08-19,2015-12-29,96.0,10.0,10.0,10.0,10.0,10.0,10.0,f,NaN,WASHINGTON,f,strict,t,t,6,1.48

In [4]:
df_reviews.head(3)

   listing_id        id        date  reviewer_id reviewer_name                                           comments
0     7202016  38917982  2015-07-19     28943674        Bianca  Cute and cozy place. Perfect location to every...
1     7202016  39087409  2015-07-20     32440555         Frank  Kelly has a great room in a very central locat...
2     7202016  39820030  2015-07-26     37722850           Ian  Very spacious apartment, and in a great neighb...

Now we will try to understand better the dataframes, looking into for their size & missing data

In [5]:
df_calendar.name="calendar"
print("No of rows and columns for "'"{}"'" are {} and {} respectively".format(df_calendar.name,df_calendar.shape[0],df_calendar.shape[1]))

No of rows and columns for "calendar" are 1393570 and 4 respectively

In [6]:
df_listingsr.name="listingsr"
print("No of rows and columns for "'"{}"'" are {} and {} respectively and the number of missing".format(df_listingsr.name[0],df_listingsr.shape[0],df_listingsr.shape[1]))

No of rows and columns for "listingsr" are 3818 and 92 respectively and the number of missing

In [7]:
df_reviews.name="reviews"
print("No of rows and columns for "'"{}"'" are {} and {} respectively".format(df_reviews.name,df_reviews.shape[0],df_reviews.shape[1]))

No of rows and columns for "reviews" are 84849 and 6 respectively

Let's see the volumes of missing values for each variables in these 3 DataFrames

In [8]:
df_reviews.isnull().sum()

listing_id        0
id                0
date              0
reviewer_id       0
reviewer_name     0
comments         18
dtype: int64

In [9]:
df_calendar.isnull().sum()

listing_id         0
date               0
available          0
price         459028
dtype: int64

In [10]:
df_listingsr.isnull().sum()

id                                     0
listing_url                            0
scrape_id                              0
last_scraped                           0
name                                   0
summary                              177
space                                569
description                            0
experiences_offered                    0
neighborhood_overview               1032
notes                               1606
transit                              934
thumbnail_url                        320
medium_url                           320
picture_url                            0
xl_picture_url                       320
host_id                                0
host_url                               0
host_name                              2
host_since                             2
host_location                          8
host_about                           859
host_response_time                   523
host_response_rate                   523
host_acceptance_rate                 773
host_is_superhost                      2
host_thumbnail_url                     2
host_picture_url                       2
host_neighbourhood                   300
host_listings_count                    2
host_total_listings_count              2
host_verifications                     0
host_has_profile_pic                   2
host_identity_verified                 2
street                                 0
neighbourhood                        416
neighbourhood_cleansed                 0
neighbourhood_group_cleansed           0
city                                   0
state                                  0
zipcode                                7
market                                 0
smart_location                         0
country_code                           0
country                                0
latitude                               0
longitude                              0
is_location_exact                      0
property_type                          1
room_type                              0
accommodates                           0
bathrooms                             16
bedrooms                               6
beds                                   1
bed_type                               0
amenities                              0
square_feet                         3721
price                                  0
weekly_price                        1809
monthly_price                       2301
security_deposit                    1952
cleaning_fee                        1030
guests_included                        0
extra_people                           0
minimum_nights                         0
maximum_nights                         0
calendar_updated                       0
has_availability                       0
availability_30                        0
availability_60                        0
availability_90                        0
availability_365                       0
calendar_last_scraped                  0
number_of_reviews                      0
first_review                         627
last_review                          627
review_scores_rating                 647
review_scores_accuracy               658
review_scores_cleanliness            653
review_scores_checkin                658
review_scores_communication          651
review_scores_location               655
review_scores_value                  656
requires_license                       0
license                             3818
jurisdiction_names                     0
instant_bookable                       0
cancellation_policy                    0
require_guest_profile_picture          0
require_guest_phone_verification       0
calculated_host_listings_count         0
reviews_per_month                    627
dtype: int64




Let's have better view on the information that exist in the df_listingsr DataFrame.

In [11]:
df_listingsr.describe(include='all')

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,thumbnail_url,medium_url,picture_url,xl_picture_url,host_id,host_url,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_thumbnail_url,host_picture_url,host_neighbourhood,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,street,neighbourhood,neighbourhood_cleansed,neighbourhood_group_cleansed,city,state,zipcode,market,smart_location,country_code,country,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,calendar_last_scraped,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,license,jurisdiction_names,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
count,3.818000e+03,3818,3.818000e+03,3818,3818,3641,3249,3818,3818,2786,2212,2884,3498,3498,3818,3498,3.818000e+03,3818,3816,3816,3810,2959,3295,3295,3045,3816,3816,3816,3518,3816.000000,3816.000000,3818,3816,3816,3818,3402,3818,3818,3818,3818,3811,3818,3818,3818,3818,3818.000000,3818.000000,3818,3817,3818,3818.000000,3802.000000,3812.000000,3817.000000,3818,3818,97.000000,3818,2009,1517,1866,2788,3818.000000,3818,3818.000000,3818.000000,3818,3818,3818.000000,3818.000000,3818.000000,3818.000000,3818,3818.000000,3191,3191,3171.000000,3160.000000,3165.000000,3160.000000,3167.000000,3163.000000,3162.000000,3818,0.0,3818,3818,3818,3818,3818,3818.000000,3191.000000
unique,NaN,3818,NaN,1,1,3478,3119,3742,1,2506,1999,2574,3498,3498,3818,3498,NaN,2751,1466,1380,120,2011,4,45,2,2,2743,2743,102,NaN,NaN,116,2,2,1442,81,87,17,7,2,28,1,7,1,1,NaN,NaN,2,16,3,NaN,NaN,NaN,NaN,5,3284,NaN,273,395,356,46,118,NaN,45,NaN,NaN,34,1,NaN,NaN,NaN,NaN,1,NaN,984,321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,1,2,3,2,2,NaN,NaN
top,NaN,https://www.airbnb.com/rooms/670021,NaN,2016-01-04,listingsr,This is a modern fully-furnished studio apartm...,"*Note: This fall, there will be major renovati...",Our space is a mix of a hostel and a home. We ...,none,Wallingford is a mostly-residential neighborho...,All of our rentals are fully licensed and regu...,Convenient public transportation. The location...,https://a0.muscache.com/ac/pictures/74628865/2...,https://a1.muscache.com/im/pictures/61301543/f...,https://a0.muscache.com/ac/pictures/60516119/6...,https://a0.muscache.com/ac/pictures/105984563/...,NaN,https://www.airbnb.com/users/show/8534462,Andrew,2013-08-30,"Seattle, Washington, United States",It would be my pleasure to share and explore t...,within an hour,100%,100%,f,https://a2.muscache.com/ac/pictures/a4d7d053-c...,https://a2.muscache.com/ac/pictures/a4d7d053-c...,Capitol Hill,NaN,NaN,"['email', 'phone', 'facebook', 'reviews', 'kba']",t,t,"1st Avenue, Seattle, WA 98101, United States",Capitol Hill,Broadway,Other neighborhoods,Seattle,WA,98122,Seattle,"Seattle, WA",US,United States,NaN,NaN,t,House,Entire home/apt,NaN,NaN,NaN,NaN,Real Bed,{},NaN,$150.00,$500.00,"$2,500.00",$100.00,$50.00,NaN,$0.00,NaN,NaN,today,t,NaN,NaN,NaN,NaN,2016-01-04,NaN,2015-09-21,2016-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,NaN,WASHINGTON,f,strict,f,f,NaN,NaN
freq,NaN,1,NaN,3818,3818,15,14,10,3818,17,39,32,1,1,1,1,NaN,46,56,51,3259,46,1692,2371,3044,3038,46,46,405,NaN,NaN,595,3809,2997,30,351,397,794,3810,3817,420,3818,3810,3818,3818,NaN,NaN,3412,1733,2541,NaN,NaN,NaN,NaN,3657,45,NaN,162,94,66,348,310,NaN,2048,NaN,NaN,706,3818,NaN,NaN,NaN,NaN,3818,NaN,25,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3818,NaN,3818,3227,1417,3497,3443,NaN,NaN
mean,5.550111e+06,NaN,2.016010e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.578556e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.157757,7.157757,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.628961,-122.333103,NaN,NaN,NaN,3.349398,1.259469,1.307712,1.735394,NaN,NaN,854.618557,NaN,NaN,NaN,NaN,NaN,1.672603,NaN,2.369303,780.447617,NaN,NaN,16.786276,36.814825,58.082504,244.772656,NaN,22.223415,NaN,NaN,94.539262,9.636392,9.556398,9.786709,9.809599,9.608916,9.452245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.946307,2.078919
std,2.962660e+06,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.458382e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.628149,28.628149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.043052,0.031745,NaN,NaN,NaN,1.977599,0.590369,0.883395,1.139480,NaN,NaN,671.404893,NaN,NaN,NaN,NaN,NaN,1.311040,NaN,16.305902,1683.589007,NaN,NaN,12.173637,23.337541,34.063845,126.772526,NaN,37.730892,NaN,NaN,6.606083,0.698031,0.797274,0.595499,0.568211,0.629053,0.750259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.893029,1.822348
min,3.335000e+03,NaN,2.016010e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.193000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.505088,-122.417219,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,NaN,NaN,20.000000,2.000000,3.000000,2.000000,2.000000,4.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.020000
25%,3.258256e+06,NaN,2.016010e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.275204e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.609418,-122.354320,NaN,NaN,NaN,2.000000,1.000000,1.000000,1.000000,NaN,NaN,420.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,60.000000,NaN,NaN,2.000000,13.000000,28.000000,124.000000,NaN,2.000000,NaN,NaN,93.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.695000
50%,6.118244e+06,NaN,2.016010e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.055814e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.623601,-122.328874,NaN,NaN,NaN,3.000000,1.000000,1.000000,1.000000,NaN,NaN,750.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,2.000000,1125.000000,NaN,NaN,20.000000,46.000000,73.000000,308.000000,NaN,9.000000,NaN,NaN,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.540000
75%,8.035127e+06,NaN,2.016010e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.590309e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.662694,-122.310800,NaN,NaN,NaN,4.000000,1.000000,2.000000,2.000000,NaN,NaN,1200.000000,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,2.000000,1125.000000,NaN,NaN,30.000000,59.000000,89.000000,360.000000,NaN,26.000000,NaN,NaN,99.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,3.000000
max,1.034016e+07,NaN,2.016010e+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.320861e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,502.000000,502.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.733358,-122.240607,NaN,NaN,NaN,16.000000,8.000000,7.000000,15.000000,NaN,NaN,3000.000000,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,1000.000000,100000.000000,NaN,NaN,30.000000,60.000000,90.000000,365.000000,NaN,474.000000,NaN,NaN,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.000000,12.150000

We will keep only the columns that seem manageable and have interesting info.
With the term manage-able information we mean those categorical variables that have a relatively low number of unique values.

In [12]:
df_list=pd.DataFrame(
df_listingsr[['id','host_response_time','host_response_rate','host_acceptance_rate','host_is_superhost','reviews_per_month',
'host_neighbourhood','host_listings_count','host_total_listings_count','host_has_profile_pic','host_identity_verified',
'neighbourhood_group_cleansed','smart_location','latitude','longitude','is_location_exact','property_type','room_type',
'accommodates','bathrooms','bedrooms','beds','bed_type','amenities','square_feet','price','weekly_price','monthly_price',
'security_deposit','cleaning_fee','guests_included','extra_people','minimum_nights','maximum_nights','calendar_updated',
'has_availability','availability_30','availability_60','availability_90','availability_365','number_of_reviews','first_review',
'last_review','review_scores_rating','review_scores_accuracy','review_scores_cleanliness','review_scores_checkin',
'review_scores_communication','review_scores_location','review_scores_value','requires_license','instant_bookable',
'cancellation_policy','require_guest_profile_picture','require_guest_phone_verification','calculated_host_listings_count']]
)

df_list.describe(include='all')

,id,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,reviews_per_month,host_neighbourhood,host_listings_count,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_group_cleansed,smart_location,latitude,longitude,is_location_exact,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,has_availability,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,requires_license,instant_bookable,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count
count,3.818000e+03,3295,3295,3045,3816,3191.000000,3518,3816.000000,3816.000000,3816,3816,3818,3818,3818.000000,3818.000000,3818,3817,3818,3818.000000,3802.000000,3812.000000,3817.000000,3818,3818,97.000000,3818,2009,1517,1866,2788,3818.000000,3818,3818.000000,3818.000000,3818,3818,3818.000000,3818.000000,3818.000000,3818.000000,3818.000000,3191,3191,3171.000000,3160.000000,3165.000000,3160.000000,3167.000000,3163.000000,3162.000000,3818,3818,3818,3818,3818,3818.000000
unique,NaN,4,45,2,2,NaN,102,NaN,NaN,2,2,17,7,NaN,NaN,2,16,3,NaN,NaN,NaN,NaN,5,3284,NaN,273,395,356,46,118,NaN,45,NaN,NaN,34,1,NaN,NaN,NaN,NaN,NaN,984,321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,3,2,2,NaN
top,NaN,within an hour,100%,100%,f,NaN,Capitol Hill,NaN,NaN,t,t,Other neighborhoods,"Seattle, WA",NaN,NaN,t,House,Entire home/apt,NaN,NaN,NaN,NaN,Real Bed,{},NaN,$150.00,$500.00,"$2,500.00",$100.00,$50.00,NaN,$0.00,NaN,NaN,today,t,NaN,NaN,NaN,NaN,NaN,2015-09-21,2016-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,f,strict,f,f,NaN
freq,NaN,1692,2371,3044,3038,NaN,405,NaN,NaN,3809,2997,794,3810,NaN,NaN,3412,1733,2541,NaN,NaN,NaN,NaN,3657,45,NaN,162,94,66,348,310,NaN,2048,NaN,NaN,706,3818,NaN,NaN,NaN,NaN,NaN,25,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3818,3227,1417,3497,3443,NaN
mean,5.550111e+06,NaN,NaN,NaN,NaN,2.078919,NaN,7.157757,7.157757,NaN,NaN,NaN,NaN,47.628961,-122.333103,NaN,NaN,NaN,3.349398,1.259469,1.307712,1.735394,NaN,NaN,854.618557,NaN,NaN,NaN,NaN,NaN,1.672603,NaN,2.369303,780.447617,NaN,NaN,16.786276,36.814825,58.082504,244.772656,22.223415,NaN,NaN,94.539262,9.636392,9.556398,9.786709,9.809599,9.608916,9.452245,NaN,NaN,NaN,NaN,NaN,2.946307
std,2.962660e+06,NaN,NaN,NaN,NaN,1.822348,NaN,28.628149,28.628149,NaN,NaN,NaN,NaN,0.043052,0.031745,NaN,NaN,NaN,1.977599,0.590369,0.883395,1.139480,NaN,NaN,671.404893,NaN,NaN,NaN,NaN,NaN,1.311040,NaN,16.305902,1683.589007,NaN,NaN,12.173637,23.337541,34.063845,126.772526,37.730892,NaN,NaN,6.606083,0.698031,0.797274,0.595499,0.568211,0.629053,0.750259,NaN,NaN,NaN,NaN,NaN,5.893029
min,3.335000e+03,NaN,NaN,NaN,NaN,0.020000,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,47.505088,-122.417219,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,1.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,20.000000,2.000000,3.000000,2.000000,2.000000,4.000000,2.000000,NaN,NaN,NaN,NaN,NaN,1.000000
25%,3.258256e+06,NaN,NaN,NaN,NaN,0.695000,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,47.609418,-122.354320,NaN,NaN,NaN,2.000000,1.000000,1.000000,1.000000,NaN,NaN,420.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,60.000000,NaN,NaN,2.000000,13.000000,28.000000,124.000000,2.000000,NaN,NaN,93.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,NaN,NaN,NaN,NaN,NaN,1.000000
50%,6.118244e+06,NaN,NaN,NaN,NaN,1.540000,NaN,1.000000,1.000000,NaN,NaN,NaN,NaN,47.623601,-122.328874,NaN,NaN,NaN,3.000000,1.000000,1.000000,1.000000,NaN,NaN,750.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,2.000000,1125.000000,NaN,NaN,20.000000,46.000000,73.000000,308.000000,9.000000,NaN,NaN,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,1.000000
75%,8.035127e+06,NaN,NaN,NaN,NaN,3.000000,NaN,3.000000,3.000000,NaN,NaN,NaN,NaN,47.662694,-122.310800,NaN,NaN,NaN,4.000000,1.000000,2.000000,2.000000,NaN,NaN,1200.000000,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,2.000000,1125.000000,NaN,NaN,30.000000,59.000000,89.000000,360.000000,26.000000,NaN,NaN,99.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,2.000000
max,1.034016e+07,NaN,NaN,NaN,NaN,12.150000,NaN,502.000000,502.000000,NaN,NaN,NaN,NaN,47.733358,-122.240607,NaN,NaN,NaN,16.000000,8.000000,7.000000,15.000000,NaN,NaN,3000.000000,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,1000.000000,100000.000000,NaN,NaN,30.000000,60.000000,90.000000,365.000000,474.000000,NaN,NaN,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,NaN,NaN,NaN,NaN,37.000000

These columns:

host_is_superhost
host_has_profile_pic
host_identity_verified
is_location_exact
has_availability
requires_license
instant_bookable
require_guest_profile_picture
require_guest_phone_verification
host_acceptance_rate

are essetntially booleans. So, we will create new boolean columns adding the suffix '_bool' in their names
and then we will drop these columns, keeping only the respective generated boolean columns

In [13]:
list=['host_is_superhost',
'host_has_profile_pic',
'host_identity_verified',
'is_location_exact',
'has_availability',
'requires_license',
'instant_bookable',
'require_guest_profile_picture',
'require_guest_phone_verification']

for col in list:
    df_list[col+'_bool']=np.where(df_list[col]=='t', True, False)
    df_list.drop([col],axis=1,inplace=True)

    
df_list['host_acceptance_rate'+'_bool']=np.where(df_list['host_acceptance_rate']=='100%', True, False)
df_list.drop(['host_acceptance_rate'],axis=1,inplace=True)

df_list.describe(include='all')

,id,host_response_time,host_response_rate,reviews_per_month,host_neighbourhood,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,smart_location,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,price,weekly_price,monthly_price,security_deposit,cleaning_fee,guests_included,extra_people,minimum_nights,maximum_nights,calendar_updated,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,cancellation_policy,calculated_host_listings_count,host_is_superhost_bool,host_has_profile_pic_bool,host_identity_verified_bool,is_location_exact_bool,has_availability_bool,requires_license_bool,instant_bookable_bool,require_guest_profile_picture_bool,require_guest_phone_verification_bool,host_acceptance_rate_bool
count,3.818000e+03,3295,3295,3191.000000,3518,3816.000000,3816.000000,3818,3818,3818.000000,3818.000000,3817,3818,3818.000000,3802.000000,3812.000000,3817.000000,3818,3818,97.000000,3818,2009,1517,1866,2788,3818.000000,3818,3818.000000,3818.000000,3818,3818.000000,3818.000000,3818.000000,3818.000000,3818.000000,3191,3191,3171.000000,3160.000000,3165.000000,3160.000000,3167.000000,3163.000000,3162.000000,3818,3818.000000,3818,3818,3818,3818,3818,3818,3818,3818,3818,3818
unique,NaN,4,45,NaN,102,NaN,NaN,17,7,NaN,NaN,16,3,NaN,NaN,NaN,NaN,5,3284,NaN,273,395,356,46,118,NaN,45,NaN,NaN,34,NaN,NaN,NaN,NaN,NaN,984,321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,2,2,2,2,1,1,2,2,2,2
top,NaN,within an hour,100%,NaN,Capitol Hill,NaN,NaN,Other neighborhoods,"Seattle, WA",NaN,NaN,House,Entire home/apt,NaN,NaN,NaN,NaN,Real Bed,{},NaN,$150.00,$500.00,"$2,500.00",$100.00,$50.00,NaN,$0.00,NaN,NaN,today,NaN,NaN,NaN,NaN,NaN,2015-09-21,2016-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,strict,NaN,False,True,True,True,True,False,False,False,False,True
freq,NaN,1692,2371,NaN,405,NaN,NaN,794,3810,NaN,NaN,1733,2541,NaN,NaN,NaN,NaN,3657,45,NaN,162,94,66,348,310,NaN,2048,NaN,NaN,706,NaN,NaN,NaN,NaN,NaN,25,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1417,NaN,3040,3809,2997,3412,3818,3818,3227,3497,3443,3044
mean,5.550111e+06,NaN,NaN,2.078919,NaN,7.157757,7.157757,NaN,NaN,47.628961,-122.333103,NaN,NaN,3.349398,1.259469,1.307712,1.735394,NaN,NaN,854.618557,NaN,NaN,NaN,NaN,NaN,1.672603,NaN,2.369303,780.447617,NaN,16.786276,36.814825,58.082504,244.772656,22.223415,NaN,NaN,94.539262,9.636392,9.556398,9.786709,9.809599,9.608916,9.452245,NaN,2.946307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.962660e+06,NaN,NaN,1.822348,NaN,28.628149,28.628149,NaN,NaN,0.043052,0.031745,NaN,NaN,1.977599,0.590369,0.883395,1.139480,NaN,NaN,671.404893,NaN,NaN,NaN,NaN,NaN,1.311040,NaN,16.305902,1683.589007,NaN,12.173637,23.337541,34.063845,126.772526,37.730892,NaN,NaN,6.606083,0.698031,0.797274,0.595499,0.568211,0.629053,0.750259,NaN,5.893029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,3.335000e+03,NaN,NaN,0.020000,NaN,1.000000,1.000000,NaN,NaN,47.505088,-122.417219,NaN,NaN,1.000000,0.000000,0.000000,1.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,1.000000,1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,20.000000,2.000000,3.000000,2.000000,2.000000,4.000000,2.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,3.258256e+06,NaN,NaN,0.695000,NaN,1.000000,1.000000,NaN,NaN,47.609418,-122.354320,NaN,NaN,2.000000,1.000000,1.000000,1.000000,NaN,NaN,420.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,1.000000,60.000000,NaN,2.000000,13.000000,28.000000,124.000000,2.000000,NaN,NaN,93.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,6.118244e+06,NaN,NaN,1.540000,NaN,1.000000,1.000000,NaN,NaN,47.623601,-122.328874,NaN,NaN,3.000000,1.000000,1.000000,1.000000,NaN,NaN,750.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,2.000000,1125.000000,NaN,20.000000,46.000000,73.000000,308.000000,9.000000,NaN,NaN,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,8.035127e+06,NaN,NaN,3.000000,NaN,3.000000,3.000000,NaN,NaN,47.662694,-122.310800,NaN,NaN,4.000000,1.000000,2.000000,2.000000,NaN,NaN,1200.000000,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,2.000000,1125.000000,NaN,30.000000,59.000000,89.000000,360.000000,26.000000,NaN,NaN,99.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.034016e+07,NaN,NaN,12.150000,NaN,502.000000,502.000000,NaN,NaN,47.733358,-122.240607,NaN,NaN,16.000000,8.000000,7.000000,15.000000,NaN,NaN,3000.000000,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,1000.000000,100000.000000,NaN,30.000000,60.000000,90.000000,365.000000,474.000000,NaN,NaN,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,37.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

These columns bear numeric information about prices in dollars:

price

weekly_price

monthly_price

security_deposit

cleaning_fee

extra_people

We will create a loop where we are going to create new variable in place of the above ones.
New variables will be numerical, without the $ sign in their values.

In [14]:
import locale
locale.setlocale( locale.LC_ALL, 'en_US.UTF-8' ) 

list=['price',
'weekly_price',
'monthly_price',
'security_deposit',
'cleaning_fee',
'extra_people'
]

for var in list:
    lst=[]
    df_list[var]=df_list[var].fillna('$-1.00')
    for index, row in df_list.iterrows():
        lst.append(locale.atoi(row[var][1:-3]))    
    df_list[var+'_dollar']=lst
    print(df_list[[var,var+'_dollar']].head(2))
    df_list[var+'_dollar']=np.where(df_list[var+'_dollar']==-1, np.nan, df_list[var+'_dollar'])
    df_list.drop([var],axis=1,inplace=True)
    print(df_list[[var+'_dollar']].head(2))

     price  price_dollar
0   $85.00            85
1  $150.00           150
   price_dollar
0          85.0
1         150.0
  weekly_price  weekly_price_dollar
0       $-1.00                   -1
1    $1,000.00                 1000
   weekly_price_dollar
0                  NaN
1               1000.0
  monthly_price  monthly_price_dollar
0        $-1.00                    -1
1     $3,000.00                  3000
   monthly_price_dollar
0                   NaN
1                3000.0
  security_deposit  security_deposit_dollar
0           $-1.00                       -1
1          $100.00                      100
   security_deposit_dollar
0                      NaN
1                    100.0
  cleaning_fee  cleaning_fee_dollar
0       $-1.00                   -1
1       $40.00                   40
   cleaning_fee_dollar
0                  NaN
1                 40.0
  extra_people  extra_people_dollar
0        $5.00                    5
1        $0.00                    0
   extra_people_dollar
0                  5.0
1                  0.0

We will apply the same concept in order to tranform column:
'host_response_rate' into a numerical, deleting the percentage sign

In [15]:
lst=[]
df_list.host_response_rate=df_list.host_response_rate.fillna('-1%')
for index, row in df_list.iterrows():
    lst.append(int(row.host_response_rate [:-1]))
df_list['host_response_rate_perc']=lst
print(df_list[['host_response_rate','host_response_rate_perc']].head(5))
df_list['host_response_rate_perc']=np.where(df_list['host_response_rate_perc']==-1, np.nan, df_list['host_response_rate_perc'])
df_list.drop(['host_response_rate'],axis=1,inplace=True)

df_list[['host_response_rate_perc']].head()


df_list.describe(include='all')

  host_response_rate  host_response_rate_perc
0                96%                       96
1                98%                       98
2                67%                       67
3                -1%                       -1
4               100%                      100

,id,host_response_time,reviews_per_month,host_neighbourhood,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,smart_location,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,square_feet,guests_included,minimum_nights,maximum_nights,calendar_updated,availability_30,availability_60,availability_90,availability_365,number_of_reviews,first_review,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,cancellation_policy,calculated_host_listings_count,host_is_superhost_bool,host_has_profile_pic_bool,host_identity_verified_bool,is_location_exact_bool,has_availability_bool,requires_license_bool,instant_bookable_bool,require_guest_profile_picture_bool,require_guest_phone_verification_bool,host_acceptance_rate_bool,price_dollar,weekly_price_dollar,monthly_price_dollar,security_deposit_dollar,cleaning_fee_dollar,extra_people_dollar,host_response_rate_perc
count,3.818000e+03,3295,3191.000000,3518,3816.000000,3816.000000,3818,3818,3818.000000,3818.000000,3817,3818,3818.000000,3802.000000,3812.000000,3817.000000,3818,3818,97.000000,3818.000000,3818.000000,3818.000000,3818,3818.000000,3818.000000,3818.000000,3818.000000,3818.000000,3191,3191,3171.000000,3160.000000,3165.000000,3160.000000,3167.000000,3163.000000,3162.000000,3818,3818.000000,3818,3818,3818,3818,3818,3818,3818,3818,3818,3818,3818.000000,2009.000000,1517.000000,1866.000000,2788.000000,3818.000000,3295.000000
unique,NaN,4,NaN,102,NaN,NaN,17,7,NaN,NaN,16,3,NaN,NaN,NaN,NaN,5,3284,NaN,NaN,NaN,NaN,34,NaN,NaN,NaN,NaN,NaN,984,321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,2,2,2,2,1,1,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,within an hour,NaN,Capitol Hill,NaN,NaN,Other neighborhoods,"Seattle, WA",NaN,NaN,House,Entire home/apt,NaN,NaN,NaN,NaN,Real Bed,{},NaN,NaN,NaN,NaN,today,NaN,NaN,NaN,NaN,NaN,2015-09-21,2016-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,strict,NaN,False,True,True,True,True,False,False,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1692,NaN,405,NaN,NaN,794,3810,NaN,NaN,1733,2541,NaN,NaN,NaN,NaN,3657,45,NaN,NaN,NaN,NaN,706,NaN,NaN,NaN,NaN,NaN,25,94,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1417,NaN,3040,3809,2997,3412,3818,3818,3227,3497,3443,3044,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,5.550111e+06,NaN,2.078919,NaN,7.157757,7.157757,NaN,NaN,47.628961,-122.333103,NaN,NaN,3.349398,1.259469,1.307712,1.735394,NaN,NaN,854.618557,1.672603,2.369303,780.447617,NaN,16.786276,36.814825,58.082504,244.772656,22.223415,NaN,NaN,94.539262,9.636392,9.556398,9.786709,9.809599,9.608916,9.452245,NaN,2.946307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.976166,788.481832,2613.336190,287.610397,61.710904,10.667627,94.886798
std,2.962660e+06,NaN,1.822348,NaN,28.628149,28.628149,NaN,NaN,0.043052,0.031745,NaN,NaN,1.977599,0.590369,0.883395,1.139480,NaN,NaN,671.404893,1.311040,16.305902,1683.589007,NaN,12.173637,23.337541,34.063845,126.772526,37.730892,NaN,NaN,6.606083,0.698031,0.797274,0.595499,0.568211,0.629053,0.750259,NaN,5.893029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90.250022,532.352269,1722.267981,270.222690,48.830341,17.585922,11.866705
min,3.335000e+03,NaN,0.020000,NaN,1.000000,1.000000,NaN,NaN,47.505088,-122.417219,NaN,NaN,1.000000,0.000000,0.000000,1.000000,NaN,NaN,0.000000,0.000000,1.000000,1.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,20.000000,2.000000,3.000000,2.000000,2.000000,4.000000,2.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,100.000000,500.000000,95.000000,5.000000,0.000000,17.000000
25%,3.258256e+06,NaN,0.695000,NaN,1.000000,1.000000,NaN,NaN,47.609418,-122.354320,NaN,NaN,2.000000,1.000000,1.000000,1.000000,NaN,NaN,420.000000,1.000000,1.000000,60.000000,NaN,2.000000,13.000000,28.000000,124.000000,2.000000,NaN,NaN,93.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75.000000,455.000000,1512.000000,150.000000,25.000000,0.000000,98.000000
50%,6.118244e+06,NaN,1.540000,NaN,1.000000,1.000000,NaN,NaN,47.623601,-122.328874,NaN,NaN,3.000000,1.000000,1.000000,1.000000,NaN,NaN,750.000000,1.000000,2.000000,1125.000000,NaN,20.000000,46.000000,73.000000,308.000000,9.000000,NaN,NaN,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,650.000000,2200.000000,250.000000,50.000000,0.000000,100.000000
75%,8.035127e+06,NaN,3.000000,NaN,3.000000,3.000000,NaN,NaN,47.662694,-122.310800,NaN,NaN,4.000000,1.000000,2.000000,2.000000,NaN,NaN,1200.000000,2.000000,2.000000,1125.000000,NaN,30.000000,59.000000,89.000000,360.000000,26.000000,NaN,NaN,99.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,950.000000,3150.000000,300.000000,83.000000,20.000000,100.000000
max,1.034016e+07,NaN,12.150000,NaN,502.000000,502.000000,NaN,NaN,47.733358,-122.240607,NaN,NaN,16.000000,8.000000,7.000000,15.000000,NaN,NaN,3000.000000,15.000000,1000.000000,100000.000000,NaN,30.000000,60.000000,90.000000,365.000000,474.000000,NaN,NaN,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,NaN,37.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,6300.000000,19500.000000,5000.000000,300.000000,300.000000,100.000000

We export this DataFrame to a csv and save on the Project's folder, in order to use this for further analysis

In [16]:
df_list.to_csv('df_list.csv',index=False,header=True)